// Generated by gencpp from file lidar_perception/DetectionObjectInfo.msg
// DO NOT EDIT!


#ifndef LIDAR_PERCEPTION_MESSAGE_DETECTIONOBJECTINFO_H
#define LIDAR_PERCEPTION_MESSAGE_DETECTIONOBJECTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_perception
{
template <class ContainerAllocator>
struct DetectionObjectInfo_
{
  typedef DetectionObjectInfo_<ContainerAllocator> Type;

  DetectionObjectInfo_()
    : type(0)
    , dt_center_x(0)
    , dt_center_y(0)
    , dt_center_z(0)
    , dt_yaw(0)
    , dt_confidence(0)
    , dt_height(0)
    , dt_width(0)
    , dt_length(0)
    , dt_distance_xv(0)
    , dt_distance_yv(0)  {
    }
  DetectionObjectInfo_(const ContainerAllocator& _alloc)
    : type(0)
    , dt_center_x(0)
    , dt_center_y(0)
    , dt_center_z(0)
    , dt_yaw(0)
    , dt_confidence(0)
    , dt_height(0)
    , dt_width(0)
    , dt_length(0)
    , dt_distance_xv(0)
    , dt_distance_yv(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _dt_center_x_type;
  _dt_center_x_type dt_center_x;

   typedef uint8_t _dt_center_y_type;
  _dt_center_y_type dt_center_y;

   typedef uint8_t _dt_center_z_type;
  _dt_center_z_type dt_center_z;

   typedef uint8_t _dt_yaw_type;
  _dt_yaw_type dt_yaw;

   typedef uint8_t _dt_confidence_type;
  _dt_confidence_type dt_confidence;

   typedef uint16_t _dt_height_type;
  _dt_height_type dt_height;

   typedef uint16_t _dt_width_type;
  _dt_width_type dt_width;

   typedef uint16_t _dt_length_type;
  _dt_length_type dt_length;

   typedef int16_t _dt_distance_xv_type;
  _dt_distance_xv_type dt_distance_xv;

   typedef int16_t _dt_distance_yv_type;
  _dt_distance_yv_type dt_distance_yv;





  typedef boost::shared_ptr< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionObjectInfo_

typedef ::lidar_perception::DetectionObjectInfo_<std::allocator<void> > DetectionObjectInfo;

typedef boost::shared_ptr< ::lidar_perception::DetectionObjectInfo > DetectionObjectInfoPtr;
typedef boost::shared_ptr< ::lidar_perception::DetectionObjectInfo const> DetectionObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lidar_perception': ['/home/chenwei/HDD/lidar_perception/src/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dfed38f8f80fae69171f39ebf42bf7c";
  }

  static const char* value(const ::lidar_perception::DetectionObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dfed38f8f80fae6ULL;
  static const uint64_t static_value2 = 0x9171f39ebf42bf7cULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_perception/DetectionObjectInfo";
  }

  static const char* value(const ::lidar_perception::DetectionObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Detection\n\
uint8                        type 		           # The category of object\n\
# unknow     0\n\
# pedestrain 1\n\
# motor      2\n\
# car        3\n\
# truck      4\n\
\n\
uint8                        dt_center_x\n\
uint8                        dt_center_y\n\
uint8                        dt_center_z\n\
uint8                        dt_yaw                # The orientation angle of object\n\
uint8                        dt_confidence         # The confidence of object\n\
uint16                       dt_height             # The height of object\n\
uint16                       dt_width              # The width of object\n\
uint16                       dt_length             # The length of object\n\
int16                        dt_distance_xv        # The longitudinal distance of object to ego vehicle coordinate\n\
int16                        dt_distance_yv        # The lateral distance of object to ego vehicle coordinate\n\
";
  }

  static const char* value(const ::lidar_perception::DetectionObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.dt_center_x);
      stream.next(m.dt_center_y);
      stream.next(m.dt_center_z);
      stream.next(m.dt_yaw);
      stream.next(m.dt_confidence);
      stream.next(m.dt_height);
      stream.next(m.dt_width);
      stream.next(m.dt_length);
      stream.next(m.dt_distance_xv);
      stream.next(m.dt_distance_yv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_perception::DetectionObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_perception::DetectionObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "dt_center_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dt_center_x);
    s << indent << "dt_center_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dt_center_y);
    s << indent << "dt_center_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dt_center_z);
    s << indent << "dt_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dt_yaw);
    s << indent << "dt_confidence: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dt_confidence);
    s << indent << "dt_height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.dt_height);
    s << indent << "dt_width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.dt_width);
    s << indent << "dt_length: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.dt_length);
    s << indent << "dt_distance_xv: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dt_distance_xv);
    s << indent << "dt_distance_yv: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dt_distance_yv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PERCEPTION_MESSAGE_DETECTIONOBJECTINFO_H
